// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_environment from "./routes/api/environment.ts";
import * as $index from "./routes/index.tsx";
import * as $GettingStarted_GettingStarted from "./islands/GettingStarted/GettingStarted.tsx";
import * as $ImageDemo_ImageDemo from "./islands/ImageDemo/ImageDemo.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/environment.ts": $api_environment,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/GettingStarted/GettingStarted.tsx":
      $GettingStarted_GettingStarted,
    "./islands/ImageDemo/ImageDemo.tsx": $ImageDemo_ImageDemo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
