version: '3.8'
services:
  backend:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - fresh-stack
    depends_on:
      - mongo
  frontend:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - fresh-stack
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  mongoClientTemp:
    image: mongo:latest
    container_name: mongoClientTemp
    links:
      - mongo:mongo
    command: mongo --host mongo --eval  "db.getSiblingDB('dashboard').createUser({user:'db', pwd:'dbpass', roles:[{role:'readWrite',db:'dashboard'}]});"
    depends_on:
      - mongo

networks:
  fresh-stack:
