version: '3.8'
services:
  backend:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - fresh-stack
    depends_on:
      - mongo
  frontend:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - fresh-stack
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - fresh-stack

networks:
  fresh-stack: